<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE coches [
    <!ELEMENT coches(coche+)>
        <!ELEMENT coche(matricula, marca, modelo)>
        <!ELEMENT matricula(#PCDATA)>
        <!ELEMENT marca(#PCDATA)>
        <!ELEMENT modelo(#PCDATA)>
        <!ATTLIST modelo hibrido CDATA #REQUIRED>
]>
<coches>
    <coche>
        <matricula>FYR4769</matricula>
        <marca>FORD</marca>
        <modelo hibrido="si"></modelo>
    </coche>
    <coche>
        <matricula>LPS7483</matricula>
        <marca>HONDA</marca>
        <modelo hibrido="no"></modelo>
    </coche>
    <coche>
        <matricula>RSA</matricula>
        <marca>SEAT</marca>
        <modelo hibrido="si"></modelo>
    </coche>
</coches>